sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
      - master
notifications:
  email:
  - jayhonnold@gmail.com
node_js:
- '9.3.0'
before_install:
  - npm i -g npm@^3.8.2
before_script:
  - npm prune
script:
  - npm run test
install: npm install
