export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const LOGIN_USER_RESOLVED = 'LOGIN_USER_RESOLVED';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';

export const SIGNUP_USER_REQUESTED = 'SIGNUP_USER_REQUESTED';
export const SIGNUP_USER_RESOLVED = 'SIGNUP_USER_RESOLVED';
export const SIGNUP_USER_REJECTED = 'SIGNUP_USER_REJECTED';
