export const CONTAINER_RESIZE = "CONTAINER_RESIZE";
export const SET_USER = "SET_USER";
export const ERROR = "ERROR";
export const HIDE_ERROR = "HIDE_ERROR";
export const RESET_ACTIVE = "RESET_ACTIVE";
export const SET_ACTIVE_INDEX = "SET_ACTIVE_INDEX";

export const LOGIN_USER_REQUESTED = "LOGIN_USER_REQUESTED";
export const LOGIN_USER_RESOLVED = "LOGIN_USER_RESOLVED";
export const LOGIN_USER_REJECTED = "LOGIN_USER_REJECTED";

export const SIGNUP_USER_REQUESTED = "SIGNUP_USER_REQUESTED";
export const SIGNUP_USER_RESOLVED = "SIGNUP_USER_RESOLVED";
export const SIGNUP_USER_REJECTED = "SIGNUP_USER_REJECTED";

export const SESSIONS_REQUESTED = "SESSIONS_REQUESTED";
export const SESSIONS_RESOLVED = "SESSIONS_RESOLVED";
export const SESSIONS_REJECTED = "SESSIONS_REJECTED";

export const NEW_SESSION_REQUESTED = "NEW_SESSION_REQUESTED";
export const NEW_SESSION_RESOLVED = "NEW_SESSION_RESOLVED";
export const NEW_SESSION_REJECTED = "NEW_SESSION_REJECTED";

export const SESSION_QUESTIONS_REQUESTED = "SESSION_QUESTIONS_REQUESTED";
export const SESSION_QUESTIONS_RESOLVED = "SESSION_QUESTIONS_RESOLVED";
export const SESSION_QUESTIONS_REJECTED = "SESSION_QUESTIONS_REJECTED";

export const QUESTION_CARD_MOVED = "QUESTION_CARD_MOVED";
export const QUESTION_CARD_ADDED = "QUESTION_CARD_ADDED";
export const SESSION_SELECTED = "SESSION_SELECTED";

export const SUBMIT_SESSION_REQUESTED = "SUBMIT_SESSION_REQUESTED";
export const SUBMIT_SESSION_RESOLVED = "SUBMIT_SESSION_RESOLVED";
export const SUBMIT_SESSION_REJECTED = "SUBMIT_SESSION_REJECTED";

export const QUESTION_URL_REQUESTED = "QUESTION_URL_REQUESTED";
export const QUESTION_URL_RESOLVED = "QUESTION_URL_RESOLVED";
export const QUESTION_URL_REJECTED = "QUESTION_URL_REJECT";

export const NEW_IMAGE_REQUESTED = "NEW_IMAGE_REQUESTED";
export const NEW_IMAGE_RESOLVED = "NEW_IMAGE_RESOLVED";
export const NEW_IMAGE_REJECTED = "NEW_IMAGE_REJECTED";

export const IS_PUSHING_NEW_IMAGE = "PUSHING_NEW_IMAGE";

export const DELETE_QUESTION_REQUESTED = "DELETE_QUESTION_REQUESTED";
export const DELETE_QUESTION_RESOLVED = "DELETE_QUESTION_RESOLVED";
export const DELETE_QUESTION_REJECTED = "DELETE_QUESTION_REJECTED";

export const LOGOUT_REQUESTED = "LOGOUT_REQUESTED";
export const LOGOUT_RESOLVED = "LOGOUT_RESOLVED";
export const LOGOUT_REJECTED = "LOGOUT_REJECTED";

export const GET_ACTIVE_REQUESTED = "GET_ACTIVE_REQUESTED";
export const GET_ACTIVE_RESOLVED = "GET_ACTIVE_RESOLVED";
export const GET_ACTIVE_REJECTED = "GET_ACTIVE_REJECTED";

export const ACTIVATE_SESSION_REQUESTED = "ACTIVATE_SESSION_REQUESTED";
export const ACTIVATE_SESSION_RESOLVED = "ACTIVATE_SESSION_RESOLVED";
export const ACTIVATE_SESSION_REJECTED = "ACTIVATE_SESSION_REJECTED";

export const ACTIVATE_QUESTION_REQUESTED = "ACTIVATE_QUESTION_REQUESTED";
export const ACTIVATE_QUESTION_RESOLVED = "ACTIVATE_QUESTION_RESOLVED";
export const ACTIVATE_QUESTION_REJECTED = "ACTIVATE_QUESTION_REJECTED";

