export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const LOGIN_USER_RESOLVED = 'LOGIN_USER_RESOLVED';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';

export const SIGNUP_USER_REQUESTED = 'SIGNUP_USER_REQUESTED';
export const SIGNUP_USER_RESOLVED = 'SIGNUP_USER_RESOLVED';
export const SIGNUP_USER_REJECTED = 'SIGNUP_USER_REJECTED';

export const SESSIONS_REQUESTED = 'SESSIONS_REQUESTED';
export const SESSIONS_RESOLVED = 'SESSIONS_RESOLVED';
export const SESSIONS_REJECTED = 'SESSIONS_REJECTED';

export const NEW_SESSION_REQUESTED = 'NEW_SESSION_REQUESTED';
export const NEW_SESSION_RESOLVED = 'NEW_SESSION_RESOLVED';
export const NEW_SESSION_REJECTED = 'NEW_SESSION_REJECTED';

export const SESSION_QUESTIONS_REQUESTED = 'SESSION_QUESTIONS_REQUESTED';
export const SESSION_QUESTIONS_RESOLVED = 'SESSION_QUESTIONED_RESOLVED';
export const SESSION_QUESTIONS_REJECTED = 'SESSION_QUESTION_REJECTED';

export const QUESTION_CARD_MOVED = 'QUESTION_CARD_MOVED';
export const QUESTION_CARD_ADDED = 'QUESTION_CARD_ADDED';